name: pink_ad
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: 4.6.5
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.4
  get_storage: ^2.1.1
  circle_nav_bar: ^2.0.1+1
  smooth_page_indicator: ^1.0.1
  flutter_rating_bar: ^4.0.1
  flutter_otp_text_field: ^1.1.1
  simple_animations: ^5.0.0+3
  d_chart: ^2.2.11
  flutter_tawk: ^0.1.0
  awesome_dialog: ^3.0.2
  custom_pop_up_menu: ^1.2.4
  url_launcher: ^6.1.10
  http: ^0.13.5
  image_picker: ^0.8.7+4
  dropdown_search: ^5.0.6
  permission_handler: ^8.2.0
  multiselect: ^0.1.0






  flutter: 
    sdk: flutter
  flutter_typeahead: ^4.6.1
  listview_infinite_pagination: ^0.0.14
  searchable_listview: ^2.4.0
  chewie: ^1.7.0
  share_plus: ^7.2.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svgIcons/
    - assets/tenserflow/

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family:  Gilroy-ExtraBold
      fonts:
         - asset: assets/fonts/Radomir Tinkov - Gilroy-ExtraBold.otf
    - family:  Gilroy-Light
      fonts:
         - asset: assets/fonts/Radomir Tinkov - Gilroy-Light.otf

