name: pink_ad
version: 1.1.12+12
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  app_links: ^3.5.0
  awesome_dialog: ^3.0.2
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  chewie: ^1.7.0
  circle_nav_bar: ^2.0.1+1
  cupertino_icons: ^1.0.5
  custom_pop_up_menu: ^1.2.4
  device_preview: ^1.1.0
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.4
  flutter_typeahead: ^4.6.1
  get: 4.6.5
  get_storage: ^2.1.1
  http: ^1.1.0
  image_picker: ^0.8.7+4
  listview_infinite_pagination: ^0.0.14
  loader_overlay: ^4.0.0
  multiselect: ^0.1.0
  permission_handler: ^8.2.0
  pull_to_refresh: ^2.0.0
  share_plus: ^7.2.1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svgIcons/
    - assets/tenserflow/

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Gilroy-ExtraBold
      fonts:
        - asset: assets/fonts/Radomir Tinkov - Gilroy-ExtraBold.otf
    - family: Gilroy-Light
      fonts:
        - asset: assets/fonts/Radomir Tinkov - Gilroy-Light.otf
